"""init

Revision ID: 480d8e785b33
Revises: 
Create Date: 2026-06-07 13:54:02.244518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480d8e785b33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME', sa.String(), nullable=False),
    sa.Column('EMAIL', sa.String(), nullable=False),
    sa.Column('PASSWORD', sa.String(), nullable=False),
    sa.Column('ACTIVE', sa.Boolean(), nullable=True),
    sa.Column('ADMIN', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ORDERS',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('STATUS', sa.String(), nullable=True),
    sa.Column('USER', sa.Integer(), nullable=True),
    sa.Column('PRICE', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['USER'], ['USERS.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ITEMS_ORDER',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('QUANTITY', sa.Integer(), nullable=True),
    sa.Column('TOPPING', sa.String(), nullable=True),
    sa.Column('SIZE', sa.String(), nullable=True),
    sa.Column('PRICE_ITEM', sa.Float(), nullable=True),
    sa.Column('ORDER_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ORDER_ID'], ['ORDERS.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ITEMS_ORDER')
    op.drop_table('ORDERS')
    op.drop_table('USERS')
    # ### end Alembic commands ###
